# -*- coding: utf-8 -*-
"""Guessgame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bECr4dzam1zk9WYyl1-9Ct8LSghrbq-Q
"""

import random

words = [ 'apple' , 'oracle', 'amazon', 'microsoft' ,'orange', 'hippopatamus', 'pomogranate',]

#choose random word from list
guessed_word = random.choice(words)
guessed_word

hint=guessed_word[0]+guessed_word[-1]
hint

store_g_1=[]
try_p=6
a=input('Enter Your Name: ')
print('Welcome To The Game World',a)
print('We are going to give you 6 attempts for guessing')

for guess in range(try_p):
  while True:
    letter = input('Guess the letter:')

    if len(letter) ==1:
      break

    else:
      print('Oops! Please Guess a letter!')

  if letter in guessed_word:
    print('yeah!')
    store_g_1.append(letter)
  else:
    print('nah!')

  if guess==3:
    print()
    clue_request = input('Would you like a Clue?')
    if clue_request.lower().startswith('y'):
      print()
      print('CLUE: The first and last letter of the word is:' ,hint)
    else:
      print('You are very confident!')

print()
print('''Now Let's see What have you guessed so far, You have guessed:''',len(store_g_1),'Letters correctly.')
print('These Letters are:',store_g_1)

word_guess = input('Guess the whole word:')
if word_guess.lower() == guessed_word:
  print('Congrats! You Are Right')
else:
  print('Sorry! The Answer Was', guessed_word)

print()
input('Please Press Enter to Leave the Game')